In [7]:
import numpy as np
import pandas as pd
from pandas import *
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import axes3d
from mpl_toolkits import mplot3d
from sklearn.metrics import r2_score,mean_squared_error

In [8]:
def normal(X):    
    return (X-X.mean(axis=0))/X.std(axis=0)    

In [9]:
df = pd.read_csv("C:/Users/PAPAM/Desktop/FODS/3D_spatial_network.txt",sep=",",header=None)
t=df.iloc[:,3]
t.head()
t=np.c_[t]
X=df.iloc[:,1:3]
X.head()
X=np.c_[X]
X=normal(X)
t=normal(t)
# X= np.c_[np.ones((len(X), 1)), X]

In [10]:
class polyreg:
    def __init__(self,x,eta=0.01,n=500):
        self.n=n
        self.eta=eta
        self.newx = np.empty(shape=[x.shape[0],0])
    def polycoeff(self,deg=1):
        self.pow =[] 
        for i in range(deg+1):
            for j in range(i+1):
                self.pow.append([i-j,j])
        print(self.pow)                    
    def buildpoly(self,x,y):
        m = x.shape[0]
        for j in range(len(self.pow)):
            temp = []
            for i in range(m):
                x1 = (x[i][0])**(self.pow[j][0])
                x2 = (x[i][1])**(self.pow[j][1])
                temp.append([x1*x2])
            matx=np.array(temp)
            matx=np.c_[matx]
            self.newx = np.append(self.newx,matx,axis=1)
            self.newx=np.c_[self.newx]
        print(self.newx)
        print(self.newx.shape)
    def polyfit(self,x,y):
        m = x.shape[0]
        self.cost_ = []
        self.rmse_ = []
        self.r2_ = []
        self.w_ = np.random.randn(len(self.pow), 1)
        for i in range(self.n):
            y_pred = np.dot(self.newx,self.w_)
            residuals = y_pred - y
            gradient_vector = np.dot(self.newx.T, residuals)
            self.w_ -= (self.eta / m) * gradient_vector
            cost = np.sum((residuals ** 2)) / (2 * m)            
            self.cost_.append(cost)
            self.rmse_.append((cost*2)**(0.5))
            ssr = np.sum((residuals)**2)
            sst = np.sum((y - np.mean(y))**2)
            self.r2_.append(1 - (ssr/sst))
    def predict(self,x):
        m = x.shape[0]
        predx = np.empty(shape=[x.shape[0],0])
        for j in range(len(self.pow)):
            temp = []
            for i in range(m):
                x1 = (x[i][0])**(A.pow[j][0])
                x2 = (x[i][1])**(A.pow[j][1])
                temp.append([x1*x2])
            matx=np.array(temp)
            matx=np.c_[matx]
            predx = np.append(predx,matx,axis=1)
            predx=np.c_[predx]
        y_pred = np.dot(predx,self.w_)
        return y_pred

In [11]:
A =polyreg(X,0.01,1000) 

In [12]:
A.polycoeff(1)

[[0, 0], [1, 0], [0, 1]]


In [13]:
A.buildpoly(X,t)

[[ 1.         -0.60889267 -1.18448203]
 [ 1.         -0.60835102 -1.18516326]
 [ 1.         -0.60777702 -1.18562616]
 ...
 [ 1.          0.32386076  1.43541988]
 [ 1.          0.33736076  1.42380211]
 [ 1.          0.33731693  1.42501463]]
(434874, 3)


In [14]:
A.polyfit(X,t)

In [15]:
A.w_

array([[ 8.81151691e-06],
       [ 1.49784457e-01],
       [-1.90030153e-01]])

In [16]:
A.cost_[-1]

0.48677336124857473

In [17]:
A.rmse_[-1]

0.986684712812127

In [18]:
A.r2_[-1]

0.02645327750285098

In [19]:
y_pred=A.predict(X)

In [20]:
y_pred

array([[ 0.13389346],
       [ 0.13410404],
       [ 0.13427798],
       ...,
       [-0.22425494],
       [-0.22002512],
       [-0.2202621 ]])